#!/usr/bin/env python
# coding: utf-8

# In[2]:


# %load ui_books_downloader.py

# Form implementation generated from reading ui file 'books_downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests
from bs4 import BeautifulSoup
import shutil

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 120, 531, 71))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 220, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.pushButton.clicked.connect(self.download_book)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "請輸入想要下載的博客來圖片頁次（中文書、商業理財、經濟/趨勢、觀念/趨勢 page1~6）"))
        self.pushButton.setText(_translate("MainWindow", "點我下載"))
        
    def download_book(self):
        keyword = self.lineEdit.text()
        
        for page in range(1, 7):
            url = 'https://www.books.com.tw/web/sys_bbotm/books/020806/?o=1&v=1&page=x'.format(keyword)
            url = url.replace('x', str(page))
            res = requests.get(url)
            soup = BeautifulSoup(res.text, 'html.parser')
            
        for pictures in soup.select('.cover'):
            fname = pictures['src'].split('/')[-1].split('&')[0] 
            res2 = requests.get(pictures['src'].split('i=')[1].split('&')[0], stream=True)
            pics = open(fname, 'wb') 
            shutil.copyfileobj(res2.raw, pics)
            pics.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

